/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as EssaysRouteImport } from './routes/essays'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as EssaysSlugRouteImport } from './routes/essays.$slug'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as AdminTopicsRouteImport } from './routes/admin.topics'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEssaysRouteImport } from './routes/admin.essays'
import { Route as AdminBooksRouteImport } from './routes/admin.books'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysRoute = EssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TopicsRoute,
} as any)
const EssaysSlugRoute = EssaysSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EssaysRoute,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BooksRoute,
} as any)
const AdminTopicsRoute = AdminTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEssaysRoute = AdminEssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/essays': typeof EssaysRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/admin/books': typeof AdminBooksRoute
  '/admin/essays': typeof AdminEssaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/books/$slug': typeof BooksSlugRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/essays': typeof EssaysRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/admin/books': typeof AdminBooksRoute
  '/admin/essays': typeof AdminEssaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/books/$slug': typeof BooksSlugRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/essays': typeof EssaysRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/admin/books': typeof AdminBooksRoute
  '/admin/essays': typeof AdminEssaysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/books/$slug': typeof BooksSlugRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/books'
    | '/essays'
    | '/topics'
    | '/admin/books'
    | '/admin/essays'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/topics'
    | '/books/$slug'
    | '/essays/$slug'
    | '/topics/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/essays'
    | '/topics'
    | '/admin/books'
    | '/admin/essays'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/topics'
    | '/books/$slug'
    | '/essays/$slug'
    | '/topics/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/books'
    | '/essays'
    | '/topics'
    | '/admin/books'
    | '/admin/essays'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/settings'
    | '/admin/topics'
    | '/books/$slug'
    | '/essays/$slug'
    | '/topics/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BooksRoute: typeof BooksRouteWithChildren
  EssaysRoute: typeof EssaysRouteWithChildren
  TopicsRoute: typeof TopicsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays': {
      id: '/essays'
      path: '/essays'
      fullPath: '/essays'
      preLoaderRoute: typeof EssaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/essays/$slug': {
      id: '/essays/$slug'
      path: '/$slug'
      fullPath: '/essays/$slug'
      preLoaderRoute: typeof EssaysSlugRouteImport
      parentRoute: typeof EssaysRoute
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof BooksRoute
    }
    '/admin/topics': {
      id: '/admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminTopicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/essays': {
      id: '/admin/essays'
      path: '/essays'
      fullPath: '/admin/essays'
      preLoaderRoute: typeof AdminEssaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRoute
  AdminEssaysRoute: typeof AdminEssaysRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTopicsRoute: typeof AdminTopicsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRoute,
  AdminEssaysRoute: AdminEssaysRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTopicsRoute: AdminTopicsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BooksRouteChildren {
  BooksSlugRoute: typeof BooksSlugRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksSlugRoute: BooksSlugRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface EssaysRouteChildren {
  EssaysSlugRoute: typeof EssaysSlugRoute
}

const EssaysRouteChildren: EssaysRouteChildren = {
  EssaysSlugRoute: EssaysSlugRoute,
}

const EssaysRouteWithChildren =
  EssaysRoute._addFileChildren(EssaysRouteChildren)

interface TopicsRouteChildren {
  TopicsSlugRoute: typeof TopicsSlugRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsSlugRoute: TopicsSlugRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BooksRoute: BooksRouteWithChildren,
  EssaysRoute: EssaysRouteWithChildren,
  TopicsRoute: TopicsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
